set -g mouse on
set -g set-clipboard on
set -g history-limit 100000
set -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
set -g status-interval 1
set -g set-titles on
set -g automatic-rename on
set -g status-left ""
set -g status-right "#[fg=#7f849c,nobold] #S  #[default] %d-%b-%y   %H:%M "
set -g status-right-length 100

# Preserve Wayland/X11 environment variables for Hyprland compatibility
set-option -g update-environment " \
    XDG_SESSION_TYPE \
    WAYLAND_DISPLAY \
    DISPLAY \
    HYPRLAND_INSTANCE_SIGNATURE \
    SSH_AUTH_SOCK \
    XAUTHORITY \
    "

# X11
#set-option -g command-alias XC="run-shell 'tmux save-buffer - | xclip -selection clipboard -i > /dev/null'"
#bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "xclip -selection clipboard -i > /dev/null"

# WAYLAND
set-option -g command-alias XC="run-shell 'tmux save-buffer - | wl-copy -t text/plain > /dev/null'"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "wl-copy -t text/plain > /dev/null"

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -ag "@catppuccin_status_${MODULE_NAME}" "#{@catppuccin_${MODULE_NAME}_text}"

set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'

